# Generated by Django 4.0.1 on 2022-03-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_home',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='orders',
            field=models.ManyToManyField(default=None, to='orders.Order'),
        ),
    ]
