# Generated by Django 4.0.1 on 2022-03-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('users', '0002_remove_customuser_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='orders',
            field=models.ManyToManyField(default=None, null=True, to='orders.Order'),
        ),
    ]
