# Generated by Django 4.0.1 on 2022-03-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_address_alter_customuser_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
