# Generated by Django 4.0.1 on 2022-02-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('group', models.CharField(choices=[('blouse', 'blouse'), ('t-shirt', 't-shirt'), ('patch', 'patch'), ('headdress', 'headdress'), ('bag', 'bag')], default='t-shirt', max_length=20)),
                ('images', models.ImageField(default='no_image.png', upload_to='product_image')),
            ],
        ),
    ]
