# Generated by Django 4.0.1 on 2022-02-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('t-shirt', 't-shirt'), ('patch', 'patch'), ('blouse', 'blouse'), ('headdress', 'headdress'), ('bag', 'bag')], default='t-shirt', max_length=20),
        ),
    ]
