# Generated by Django 4.0.1 on 2022-03-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('patch', 'patch'), ('blouse', 'blouse'), ('bag', 'bag'), ('t-shirt', 't-shirt'), ('headdress', 'headdress')], default='t-shirt', max_length=20),
        ),
    ]
