# Generated by Django 4.0.1 on 2022-03-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('bag', 'bag'), ('blouse', 'blouse'), ('t-shirt', 't-shirt'), ('headdress', 'headdress'), ('patch', 'patch')], default='t-shirt', max_length=20),
        ),
    ]
