# Generated by Django 4.0.1 on 2022-03-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('blouse', 'blouse'), ('bag', 'bag'), ('patch', 'patch'), ('headdress', 'headdress'), ('t-shirt', 't-shirt')], default='t-shirt', max_length=20),
        ),
    ]
