# Generated by Django 4.0.1 on 2022-03-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('headdress', 'headdress'), ('patch', 'patch'), ('bag', 'bag'), ('t-shirt', 't-shirt'), ('blouse', 'blouse')], default='t-shirt', max_length=20),
        ),
    ]
